### model
model_name_or_path: Qwen/Qwen2-VL-2B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: clm-auto
template: qwen2_vl
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
train_on_prompt: False

### output
output_dir: saves/qwen2_vl-7b/lora/sft
logging_steps: 1
save_steps: 6
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.0
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 0